import styled from 'styled-components'
import { TYPO, COLOR } from 'const'

const StyledFooter = styled.footer`
  color: var(${COLOR.secondary});
  margin: 96px 16px 32px;
  text-align: center;
`

function Footer() {
  return (
    <StyledFooter className={TYPO.body3}>
      Statically generated by Next.js and hosted on Github Page.
    </StyledFooter>
  )
}

export default Footer
