import styled from 'styled-components'

const StyledFooter = styled.footer`
  text-align: center;
  margin-top: 60px;
`

function Footer() {
  return (
    <StyledFooter>
      Statically generated by Next.js, hosted with Github Page
    </StyledFooter>
  )
}

export default Footer
