import styled from 'styled-components'
import { TYPO, COLOR } from '@/const'

const StyledFooter = styled.footer`
  color: var(${COLOR.lighten});
  margin: 96px 16px 32px;
  text-align: center;
`

export function Footer() {
  return (
    <StyledFooter className={TYPO.body3}>
      Statically generated by Next.js and hosted on Github Page.
      <br />
      With help from styled-components and Heroicons.
    </StyledFooter>
  )
}
